version: 2.1

orbs:
  python: circleci/python@2.0.1

jobs:
  test:
    machine:
      resource_class: gpu.nvidia.small
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: pytest

workflows:
  sample:
    jobs:
      - test
