version: 2.1

orbs:
  python: circleci/python@2.0.3
  gcp-gcr: circleci/gcp-gcr@0.15.0

jobs:
  test:
    executor:
      name: python/default
      tag: '3.9'
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run: pipenv run pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results  

  test_parallel:
    parallelism: 10 # Parallelism
    executor:
      name: python/default
      tag: '3.9'
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pipenv
      - run: pipenv run pytest $(circleci tests glob "tests/test_*.py" | circleci tests split --split-by=timings) --junitxml=test-results/junit.xml
      - store_test_results:
          path: report.xml

  test_runner:
    machine: true
    resource_class: tadashi0713/gcp
    steps:
      - checkout
      - run:
          name: Test
          command: |
            source ~/.bashrc
            pipenv install
            pipenv run pytest --junitxml=test-results/junit.xml
      - store_test_results:
          path: test-results

  deploy:
    machine: true
    resource_class: tadashi0713/gcp
    steps:
      - checkout
      - run:
          name: Test
          command: |
            source ~/.bashrc
            pipenv install
            pipenv run authbind gunicorn -b 0.0.0.0:80 app:app

workflows:
  test_and_deploy:
    jobs:
      - test
      - test_parallel:
          requires:
            - test
      # - test_runner:
      #     requires:
      #       - test
      - deploy

