version: 2.1

orbs:
  python: circleci/python@2.0.1

jobs:
  test:
    executor: python/default
    steps:
      - checkout
      - python/install-packages:
          pkg-manager: pip
      - run: pytest

workflows:
  sample:
    jobs:
      - test
